### ISSUE TITLE
🚫 Error: PostCSS plugin postcss-nested requires PostCSS 8.

### ISSUE THREAD

**Issue by MoSattler** [tailwindlabs/tailwindcss-cli#1]
When running this script without pcss as prescribed in the [docs](https://tailwindcss.com/docs/installation#using-tailwind-without-post-css) I get this error

```
   tailwindcss 2.0.1
  
   🚀 Building: src/tailwind.css
  
   🚫 Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/code/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/code/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/code/node_modules/postcss/lib/postcss.js:55:10)
    at /code/node_modules/tailwindcss/lib/util/parseObjectStyles.js:24:33
    at arrayMap (/code/node_modules/lodash/lodash.js:639:23)
    at map (/code/node_modules/lodash/lodash.js:9580:14)
    at Function.flatMap (/code/node_modules/lodash/lodash.js:9283:26)
    at parseObjectStyles (/code/node_modules/tailwindcss/lib/util/parseObjectStyles.js:23:26)
    at parseObjectStyles (/code/node_modules/tailwindcss/lib/util/parseObjectStyles.js:20:12)
    at /code/node_modules/tailwindcss/lib/util/processPlugins.js:37:123
```

Any idea what I am doing wrong?

**Comment by MoSattler** [comment]
Nevermind, I think it was an error of my side. Removing cache and node_modules + reinstalling deps fixed it
